name: Parallel Pipeline
on: [push]

jobs:
  # These jobs will run in parallel (no dependencies)
  
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          npm test
          echo "✅ Unit tests passed"

  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - name: Run linting (simulate)
        run: |
          echo "Running ESLint..."
          echo "✅ Code style looks good"

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - name: Security audit
        run: |
          echo "Running security scan..."
          npm audit --audit-level=high
          echo "✅ No security issues found"

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - name: Type checking (simulate)
        run: |
          echo "Running TypeScript checks..."
          echo "✅ Types are valid"

  # This job waits for ALL parallel jobs to complete
  integration-tests:
    needs: [unit-tests, lint-check, security-scan, type-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - name: Run integration tests
        run: |
          echo "All checks passed! Running integration tests..."
          echo "🎉 Everything looks great!"